### ISSUE TITLE
Remote Debugging Docker - Unable to Open <Breakpoint-charpfile>: File Not Found

### ISSUE THREAD

**Issue by garfbradaz** [OmniSharp/omnisharp-vscode#2724]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version:

Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

C# Extension version:
1.17.1

## Steps to reproduce

The following is for a ASP.NET Core WebAPI, that runs within Docker using `docker-compose`. I will provide the files.

1. Set breakpoints in Controller (VSCode)
2. `docker-compose -f docker-compose.dev.yml up -d --build`
3. VSCode -> Debug - > Attach to WebApi (Docker)
4. Run Postman with the payload I wanted to Debug

## Expected  behavior

1. Breakpoint is hit.
2. Controller.cs is shown when breakpoint is hit.

## Actual behaviour

1. Breakpoint is hit....but
2. I get the following error instead:

> Unable to open 'CompanyController.cs': File not found

![image](https://user-images.githubusercontent.com/959766/49325484-15a7e380-f53b-11e8-90d6-9db0fb4e0e0a.png)

The debugging itself _is_ working, so I can see the Stack and locals etc, It just when the breakpoint is thrown, the CompanyController.cs isnt shown.

Here is the support documentation:

## Dockerfile

```Dockerfile
FROM microsoft/dotnet:2.1-sdk AS build-env
ARG buildconfig
WORKDIR /app
COPY ServiceApp.WebApi.csproj .
RUN dotnet restore
COPY . .
RUN if [ "${buildconfig}" = "Debug" ]; then \
        dotnet publish -o /publish -c Debug; \
    else \
        dotnet publish -o /publish -c Release; \
    fi 

FROM microsoft/dotnet:2.1-aspnetcore-runtime
ARG buildconfig
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /publish
EXPOSE 5000
COPY --from=build-env /publish .
RUN if [ "${buildconfig}" = "Debug" ]; then \
        apt-get update && \
        apt-get install -y --no-install-recommends apt-utils && \
        apt-get install curl unzip procps -y && \
        curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /publish/vsdbg; \
     else \ 
        echo "*Whistling*"; \
    fi 
ENV DEBIAN_FRONTEND teletype
ENTRYPOINT [ "dotnet","ServiceApp.WebApi.dll" ]
```
## docker-compose-dev.yml

```YAML
version: "3"
services:
  webapi:
    image: garfbradaz/serviceapp:develop
    container_name: webapi_debug
    build:
      args:
        buildconfig: Debug
      context: ../api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27107"
```

## Launch.json
```json
        {
            "name": "Attach to webapi (Docker)",
            "type": "coreclr",
            "request": "attach",
            "sourceFileMap": {
                "/publish": "${workspaceFolder}/src/api"
            },
            "processId" : "${command:pickRemoteProcess}",
            "pipeTransport": {
                "debuggerPath": "/publish/vsdbg/vsdbg",
                "pipeProgram": "docker",
                "pipeCwd": "${workspaceFolder}/src/api",
                "quoteArgs": false,
                "pipeArgs": [
                    "exec","-i", "webapi_debug"
                ]
             }
        }
```

**Comment by garfbradaz** [comment]
# Fixed it!

Stupid me, I wasn't mounting the Source Code directory from my Windows machine _into_ the docker container itself (As I'm building within the docker container).

## Changes made
### docker-compose-dev.yml

Added:

```YAML
    volumes:
      - ../api:/app
```
This maps my `./api` directory from my to `/app` within the controller. Note, you can check this has worked by:

1. `docker exec -it <container-name> bash`
2. `cd /app`
3. `dir `

![image](https://user-images.githubusercontent.com/959766/49325915-1db75180-f542-11e8-894b-8bce2262be9f.png)

Full **docker-compose.dev.yml**:

```YAML
version: "3"
services:
  webapi:
    image: garfbradaz/serviceapp:develop
    container_name: webapi_debug
    build:
      args:
        buildconfig: Debug
      context: ../api
      dockerfile: Dockerfile
    volumes:
      - ../api:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27107"
```

### launch.json

Updated **launch.json** `sourceFileMap` property to point to the mounted volume `/app`:

```JSON
            "sourceFileMap": {
                "/app": "${workspaceFolder}/src/api"
            }
```
Full **launch.json**:

```JSON
        {
            "name": "Attach to webapi (Docker)",
            "type": "coreclr",
            "request": "attach",
            "sourceFileMap": {
                "/app": "${workspaceFolder}/src/api"
            },
            "processId" : "${command:pickRemoteProcess}",
            "pipeTransport": {
                "debuggerPath": "/publish/vsdbg/vsdbg",
                "pipeProgram": "docker",
                "pipeCwd": "${workspaceFolder}/src/api",
                "quoteArgs": false,
                "pipeArgs": [
                    "exec","-i", "webapi_debug"
                ]
             }
        }
```
